const TF2_DATA = {
    playerNames: [
  "Nebula", "Floppa", "Snail7", "WarHen", "Specimen04",
  "KrispyTheNugget", "Duck_Baesos", "Mountain Oil Enjoyer",
  "poopedmypants777", "megarayo", "SixoMan", "Skye",
  "rocket jumping loser", "alkiosavainash", "dudlee",
  "mmich456", "NEVER SOON", "snappy", "hi jo", "Wojak",
  "Sempii", "Shotgun", "dex", "mothdamn", "starleo303",
  "blackshadow", "Friday Funkin'", "GibusMann", "jose.gonzales.2007",
  "Engineer Gaming", "Xx_DarkSlayer_xX", "Pootis Spencer", "Dr. Sex",
  "scout main", "TF2 Player", "unnamed", "Valve", "Gaben",
  "SpyCrab", "Hoovy", "Rick May", "OMEGATRONIC", "DoesHotter",
  "festive hitman", "Samsung Smart Fridge", "Tax Evasion", "CEO of Racism",
  "Bread", "Soup", "Obama Gaming", "shrek", "Heavy Weapons Guy",
  "medic gf", "The Observer", "Spy", "Sniper", "Demoman",
  "pyro shark", "trolldier", "Soundsmith", "LazyPurple",
  "Uncle Dane", "Big Joey", "SolarLight", "Vorobey",
  "Zesty Jesus", "Elmaxo", "Wutville Enjoyer", "2fort 24/7",
  "trade.tf user", "scrap.tf bot 04", "Market Plandener", "Force-A-Nature",
  "Lime Scunt", "Generic Soldier Main", "crocket magnet", "w+m1",
  "f2p sniper", "aimbot?", "cheater", "vac banned", "kicked",
  "disconnected", "connecting...", "error", "missing texture",
  "Purple Checkerboard", "A Pose Scout", "Civilian Heavy", "Binoculus",
  "Potassium Bonnet", "Burning Team Captain", "Golden Pan Owner", "Saxxy Winner",
  "Developer", "Admin", "Moderator", "Owner", "Host",
  "Guest", "Player", "Human", "Bot", "AI",
  "NPC", "Enemy", "Ally", "Teammate", "Friend",
  "Rival", "Nemesis", "Target", "Victim", "Killer",
  "Pablo.gonzales.2005", "Killer_69", "PRO_GAMER_HD", "mom_said_its_my_turn",
  "xX_Sephiroth_Xx", "Kirito", "Naruto123", "sans gaming",
  "dispenser_goes_here", "nope.avi", "mentlegen", "spy_among_us"
],
    weapons: [
  "tf_projectile_rocket", "sniperrifle", "scattergun", "minigun",
  "iron_bomber", "stickybomb_launcher", "targe_charge", "nessieclub",
  "market_gardener", "bazaar_bargain", "phlogistinator", "flamethrower",
  "scorch_shot", "tomislav", "knife", "eternal_reward", "ambassador",
  "obj_sentrygun3", "world", "trigger_hurt", "smg", "fireaxe",
  "airstrike", "big_earner", "force_a_nature", "loch_n_load",
  "revolver", "pistol", "bottle", "bat", "shovel", "wrench", "bonesaw",
  "fists", "shotgun_soldier", "shotgun_pyro", "shotgun_hwg", 
  "backburner", "degreaser", "reserve_shooter", "blackbox", 
  "rocketlauncher_directhit", "cow_mangler", "beggars_bazooka", 
  "disciplinary_action", "escape_plan", "equalizer", "pain_train", 
  "ullapool_caber", "loose_cannon", "scottish_resistance", 
  "claidheamh_mor", "persian_persuader", "fryingpan", "ham_shank", 
  "natascha", "brass_beast", "huo_long_heater", "family_business", 
  "gloves_running_urgently", "fists_of_steel", "frontier_justice", 
  "robot_arm", "jag", "southern_hospitality", "rescue_ranger", 
  "blutsauger", "ubersaw", "vita_saw", "amputator", "solemn_vow", 
  "sydney_sleeper", "machina", "hitmans_heatmaker", "classic", 
  "bushwacka", "shahanshah", "tribalmans_shiv", "club", "diamondback", 
  "letranger", "kunai", "sharp_dresser", "spy_cicle", "taunt_scout", 
  "taunt_heavy", "taunt_pyro", "taunt_spy", "obj_sentrygun", 
  "obj_sentrygun2", "obj_minisentry", "tf_projectile_pipe", 
  "tf_projectile_arrow", "tf_projectile_jar", "deflect_rocket", 
  "deflect_promode", "sawmill_blade", "train", "lava",
  "golden_frying_pan", "saxxy", "prinny_machete", "batsaber", "capper"
],
    chat: [
  "woof", "meow", "no we need more spies", "nice hit",
  "scorch shot and phlog is a sin", "so mean", "Hello",
  "can we get a medic my fellow men?", "ns", "lag",
  "spy behind", "F1", "F2", "gg", "ez", "diff", "sellout",
  "kick bot", "random crits are fair and balanced", "MEDIC!",
  "w+m1 noob", "spy has dead ringer", "f1 cheater", "selling keys",
  "thanks pally", "engineer gaming", "crocket", "pootis",
  "why do we have 5 snipers?", "move that gear up", "team?",
  "nice facestab", "uber popped", "spy is gun spy", "nt",
  "scunt", "medic gf", "buying hats", "demoknight tf2",
  "spy checking", "f2 he's clean", "mge me", "tryhard",
  "heavy update when", "pyro airblast pls", "sentry down",
  "dispenser here", "thanks doc", "nice unusual", "get rekt",
  "friendly hoovy dont kill", "cap the point", "push cart",
  "hightower no cap", "market gardener", "nice ping", "cl_interp abuser",
  "pocket medic", "pop it don't drop it", "pybro", "homewrecker",
  "sentry nest ahead", "stickies on point", "intel dropped",
  "we have no engineer", "medic why", "spy is disguised as heavy",
  "lime scout", "auto balance sucks", "scramble teams", "don't kill friendlies",
  "taunt kill", "killbind", "trade server?", "selling 2 ref",
  "nice cosmetics", "bot is aimbotting", "vote kick", "sorry lag",
  "bodyshot", "nice hacks", "teleporter entrance here", "uber ready",
  "battle medic", "stop dying", "gh", "gr", "ty",
  "I swear if I die to one more random crit I am uninstalling this game",
  "can one of the 4 snipers please switch to medic or power class thanks",
  "Selling Unusual Burning Flames Team Captain 2000 keys pure only no dupes",
  "dude stop taking the health pack when you have 124 hp and I'm burning to death",
  "why is nobody pushing the cart it literally moves backward when you don't touch it",
  "selling strange killstreak festive rocket launcher for 5 keys send trade offer",
  "kick the bot in the name of our lord and savior gaben please F1",
  "medic why did you pop uber on the sniper instead of the heavy?",
  "can someone please help me with this spy sapping my sentry over and over",
  "imagine using the phlog and scorch shot and thinking you have actual skill",
  "enemy team has 3 medics and we have 4 spies and a demoknight",
  "guys the spy is disguised as me don't let him backstab you",
  "Buying all backpacks quicksell prices only paying in refined metal add me",
  "sorry guys my ping just spiked to 9000 I can't move",
  "that hitreg was absolutely broken I was clearly behind the wall",
  "please stop capping on hightower we are just trying to deathmatch",
  "looking for a pocket medic for competitive 6s pm me for discord",
  "I have full uber charge stop running away from me you idiot",
  "how did that backstab count? he was looking right at me valve pls fix",
  "everyone go left side through the tunnel they have a sentry on the right",
  "press F1 to kick the cheater he is spinning in spawn",
  "thank you for the heals medic you are the only reason we are winning",
  "demo can you please destroy the nest upstairs before we push in?",
  "bind w kill", "quit smoking", "disconnecting in 3...", "lol", "lmao",
  "cringe", "based", "ratio", "L", "W", "rip bozo",
  "skill issue", "gaming chair diff", "touch grass"
],
    errors: [
  "SetupBones: invalid bone array size (2 - needs 3)",
  "No such variable \"$fogstart\" for material \"maps/ctf_2fort/water/water_2fort_-528_-1520_-128\"",
  "No such variable \"$bloomamount\" for material \"dev/blurfiltery_nohdr\"",
  "Error! Variable \"$yellow\" is multiply defined in material \"models/workshop_partner/player/items/all_class/jackbadge/jackbadge_limited\"!",
  "No such variable \"$basetexture\" for material \"effects/rockettrailsmoke\"",
  "KeyValues Error: RecursiveLoadFromBuffer: got } in key in file materials/models/props_foliage/grass_02.vmt",
  "Model models/props_gameplay/security_fence_section01.mdl not found and models/error.mdl couldn't be loaded",
  "MP3 initialized with no sound cache",
  "Requesting texture value from var \"$dummyvar\" which is not a texture value (material: skybox/sky_dustbowl_01rt)",
  "DataTable warning: player: Could not find table \"DT_TFPlayerScoringDataExclusive\"",
  "Failed to load sound \"vo\scout_painsharp01.wav\", file probably missing from disk/repository",
  "Error: Material \"models/player/scout/scout_head\" : proxy \"AnimatedTexture\" unable to initialize!",
  "C_TFPlayer::Reset: restarting partial cycle",
  "Attempted to precache unknown particle system \"explosion_trail\"",
  "SOLID_VPHYSICS static prop with no vphysics model! (models/props_combine/combine_fence01b.mdl)",
  "CMaterial::PrecacheVars: error loading vmt file for models/props_gameplay/haybale",
  "unhandled sticker option \"sticker_path\"",
  "Error vertex file for 'models/player/scout.mdl' checksum -1234567890 should be 1234567890",
  "DispatchAsyncEvent: event id 9832 has no handler.",
  "SV_StartSound: weapons\rocket_shoot.wav not precached (0)",
  "Bad pstudiohdr in GetSequenceLinearMotion()!",
  "C_BaseEntity::SaveData: missing field 'm_hOwnerEntity'",
  "Particles: StartCapEndCap: particle system 'flamethrower_crit_red' not found",
  "Scene 'scenes/player/scout/low/taunt01.vcd' missing!"
],
    system: [
  "Lobby updated",
  "Redownloading all lightmaps",
  "Compact freed 200704 bytes",
  "Connecting to 192.168.1.10:27015...",
  "Connected to 192.168.1.10:27015",
  "Network: IP 10.0.0.5, mode MP, dedicated No, ports 27015 SV / 27005 CL",
  "VAC secure mode is activated.",
  "Parsed 354 particle systems",
  "Initializing renderer...",
  "Host_WriteConfiguration: Wrote cfg/config.cfg",
  "Using specific color correction file: materials/correction/cc_2fort.raw",
  "Server has disabled lobby reservations",
  "Disconnect: Client disconnect.",
  "Processing rates updates...",
  "Changing map to pl_upward",
  "Precomputing lighting ... Done",
  "Dropped Player from server (Disconnect by user.)",
  "Game supporting: multiplayer",
  "Writing configuration to \"config.cfg\"",
  "Client \"User\" connected (127.0.0.1:27005)."
],
    achievements: [
        "Head of the Class", "Hard to Kill", "Master of Disguise",
        "Grey Matter", "Riftwalker", "Flamethrower", "Sentry Gunner",
        "Point Clicker", "Backstabber", "Double Donk", "Flag Bearer",
        "World Traveler", "Prime Cuts", "First Blood", "Nemesis",
        "Hardcore", "Impossible!", "Gotta Cap 'Em All", "Pyromancer",
        "Caber Tosser", "Sticky Jumper", "Rocket Man", "Scout's Honor"
    ],
    items: [
        "Mann Co. Supply Crate", "Refined Metal", "Reclaimed Metal", "Scrap Metal",
        "Name Tag", "Description Tag", "Decal Tool", "Dueling Mini-Game",
        "Giftapult", "Backpack Expander", "Tour of Duty Ticket",
        "Mann Co. Store Package", "Random Craft Hat", "Secret Saxton",
        "Pile of Robo-Key Gifts", "Noise Maker - Winter Holiday",
        "Spellbook Page", "Haunted Metal Scrap", "Unusual Parsley",
        "Golden Frying Pan (Rare!)", "Australium Rocket Launcher"
    ]
};

const presets = {
  modern: { sr: 22050, hp: 300, lp: 6000, bits: 16, gain: 1.2, loss: 0, env: 'none' },
  legacy: { sr: 11025, hp: 400, lp: 3500, bits: 8,  gain: 2.5, loss: 0, env: 'room' },
  spam:   { sr: 22050, hp: 200, lp: 12000, bits: 12, gain: 12.0, loss: 0, env: 'none' }
};

const envConfigs = {
  none:   null,
  room:   [0.5, 3.0, 0.15],
  locker: [0.3, 8.0, 0.25],
  hall:   [1.5, 4.0, 0.35]
};

const FCVAR = { NONE: 0, CHEAT: 1 << 0, READONLY: 1 << 1, SERVER: 1 << 2 };